// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SensorReading {
    #[prost(string, tag = "1")]
    pub sensor_id: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub temperature: f64,
    #[prost(int64, tag = "3")]
    pub timestamp: i64,
    #[prost(string, tag = "4")]
    pub location: ::prost::alloc::string::String,
}
